# Use postgres/example user/password credentials

#version: "3.8"
#
#services:
#
#  redis:
#    image: redis/redis-stack-server:edge
#    container_name: redis-standalone
#    ports:
#      - 6379:6379

version: "3.9"

services:
  redis_test:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"

# docker exec -it redis_test redis-cli
